apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ekart
  namespace: ekart
spec:
  project: default
  source:
    repoURL: https://github.com/AmulThantharate/Ekart1
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ekart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
